/* Generated by editor.html. Do not edit this file manually. */
window.practiceContent = {
  "schemaVersion": 3,
  "colorTheme": "crimson",
  "customColors": {},
  "practiceName": "Carina Schmida, BA.pth.",
  "practitionerName": "Carina Schmida",
  "siteIcon": "assets/icon4_tiny.png",
  "navigation": {
    "home": "Startseite"
  },
  "hero": {
    "eyebrow": "Psychotherapeutin in Ausbildung unter Supervision",
    "title": "Jeder Mensch verdient es, gehört zu werden.",
    "sentence": "Ich begleite Sie einfühlsam und kompetent auf Ihrem Weg zu mehr Klarheit, Stabilität und Wohlbefinden.",
    "contactButton": "Erstgespräch anfragen",
    "titleSize": "tiny"
  },
  "heroImage": {
    "src": "assets/carina_close2.JPG",
    "alt": "Porträt von Carina Schmida",
    "layout": "landscape",
    "blend": "natural",
    "position": "center 30%",
    "mobileLayout": "portrait",
    "mobilePosition": "center 38%",
    "overlay": "soft",
    "blendWidthDesktop": 32,
    "blendWidthMobile": 28
  },
  "sections": [
    {
      "id": "psychotherapie",
      "layout": "intro",
      "internalName": "Intro",
      "navigationLabel": "Psychotherapie",
      "background": "paper",
      "customBackground": "#f7f2ef",
      "appearance": {
        "headingModeDesktop": "eyebrow",
        "headingModeMobile": "eyebrow",
        "titleSize": "standard"
      },
      "content": {
        "eyebrow": "Psychotherapie",
        "title": "",
        "intro": "Manchmal hilft es, nicht allein weitergehen zu müssen.",
        "text": "Ob bei Ängsten, Depressionen oder anderen psychischen Krisen – als Verhaltenstherapeutin unterstütze ich Sie dabei, belastende Gefühle, Gedanken und Verhaltensweisen zu erkennen und schrittweise zu verändern.\n\nRespekt, Wertschätzung und Empathie bilden die Basis unserer Zusammenarbeit. In einem sicheren, geschützten Rahmen können Sie sich öffnen, vorhandene Stärken und Ressourcen wiederentdecken, hilfreiche Strategien erlernen und neue Wege erkunden.\n\nMein Ziel ist, dass Sie mehr Klarheit und Selbstwirksamkeit gewinnen – und damit mehr Lebensfreude und Wohlbefinden in Ihr Leben einziehen können.\n\nIch würde mich freuen, Sie kennenlernen und ein Stück auf Ihrem Weg in eine möglichst unbeschwerte Zukunft begleiten zu dürfen.",
        "items": []
      }
    },
    {
      "id": "schwerpunkte",
      "layout": "topics",
      "internalName": "Schwerpunkte",
      "navigationLabel": "Schwerpunkte",
      "background": "rose",
      "customBackground": "#f7f2ef",
      "appearance": {
        "headingModeDesktop": "eyebrow",
        "headingModeMobile": "eyebrow",
        "titleSize": "standard",
        "listStyle": "gradient-pills",
        "gradientStart": "#d11137",
        "gradientEnd": "#6d0918"
      },
      "content": {
        "eyebrow": "Schwerpunkte",
        "title": "Wobei ich Sie begleiten kann.",
        "intro": "Psychotherapie ist so individuell wie die Menschen, die sie in Anspruch nehmen. Zu meinen Schwerpunkten zählen:",
        "items": [
          {
            "text": "Ängste, Zwänge und Panikattacken"
          },
          {
            "text": "Depressionen"
          },
          {
            "text": "Essstörungen"
          },
          {
            "text": "Trauma und Belastungsstörungen"
          },
          {
            "text": "Psychosomatische Beschwerden"
          },
          {
            "text": "ADHS"
          },
          {
            "text": "Krisenhafte Lebenssituationen"
          }
        ]
      }
    },
    {
      "id": "berufserfahrung",
      "layout": "timeline",
      "internalName": "Vertikale Zeitleiste",
      "navigationLabel": "Über mich",
      "background": "paper",
      "customBackground": "#f7f2ef",
      "appearance": {
        "headingModeDesktop": "eyebrow",
        "headingModeMobile": "eyebrow",
        "titleSize": "compact",
        "timelineStyle": "alternating-path"
      },
      "content": {
        "eyebrow": "Über mich",
        "title": "Psychosoziale Berufserfahrung.",
        "intro": "Als Psychotherapeutin in Ausbildung unter Supervision stehe ich im regelmäßigen fachlichen Austausch mit erfahrenen Psychotherapeut:innen.\n\nMeine bisherigen Tätigkeiten im psychosozialen Bereich:",
        "items": [
          {
            "period": "Seit 2024",
            "title": "SFU-Ambulanz für Erwachsene",
            "detail": ""
          },
          {
            "period": "Seit 2023",
            "title": "Institut Apädo",
            "detail": ""
          },
          {
            "period": "2022",
            "title": "Gerontopsychiatrische Station",
            "detail": "Klinik Donaustadt Wien"
          },
          {
            "period": "2021",
            "title": "Sozialpädagogische Kinder- und Jugend-Wohngemeinschaft",
            "detail": "Volkshilfe Wien"
          }
        ]
      }
    },
    {
      "id": "ausbildung",
      "layout": "timeline",
      "internalName": "Vertikale Zeitleiste",
      "navigationLabel": "",
      "background": "rose",
      "customBackground": "#f7f2ef",
      "appearance": {
        "headingModeDesktop": "eyebrow",
        "headingModeMobile": "eyebrow",
        "titleSize": "compact",
        "timelineStyle": "classic-lines"
      },
      "content": {
        "eyebrow": "Ausbildung",
        "title": "Ausbildung",
        "intro": "Meine psychotherapeutische und ergänzende Ausbildung:",
        "items": [
          {
            "period": "Laufend",
            "title": "Lerntherapeut*in & Kinder- und Elterncoach nach Apädo",
            "detail": ""
          },
          {
            "period": "Laufend",
            "title": "Magisterstudium der Psychotherapiewissenschaft",
            "detail": "Sigmund Freud Privatuniversität Wien"
          },
          {
            "period": "Laufend",
            "title": "Fachspezifikum Verhaltenstherapie",
            "detail": "Sigmund Freud Privatuniversität Wien"
          },
          {
            "period": "2023",
            "title": "Bakkalaureatsstudium Psychotherapiewissenschaft",
            "detail": "Sigmund Freud Privatuniversität Wien"
          },
          {
            "period": "2022",
            "title": "Psychotherapeutisches Propädeutikum",
            "detail": "HoPP Postgraduate Center, Universität Wien"
          }
        ]
      }
    },
    {
      "id": "praxis",
      "layout": "wideImage",
      "internalName": "Text über breitem Bild",
      "navigationLabel": "Praxis",
      "background": "soft",
      "customBackground": "#f7f2ef",
      "appearance": {
        "headingModeDesktop": "title",
        "headingModeMobile": "eyebrow",
        "titleSize": "standard"
      },
      "content": {
        "eyebrow": "Praxis",
        "title": "Praxis",
        "text": "Die helle, ruhige Praxis bietet einen geschützten Raum für Gespräche, neue Perspektiven und persönliche Entwicklung.",
        "imageSrc": "assets/office_horizontal.JPG",
        "imageAlt": "Heller Praxisraum mit zwei Sesseln",
        "imagePosition": "center top",
        "caption": "Praxisraum"
      }
    },
    {
      "id": "kontakt",
      "layout": "contact",
      "internalName": "Kontaktblock mit Karte",
      "navigationLabel": "Kontakt",
      "background": "dark",
      "customBackground": "#f7f2ef",
      "appearance": {
        "headingModeDesktop": "eyebrow",
        "headingModeMobile": "eyebrow",
        "titleSize": "standard"
      },
      "content": {
        "eyebrow": "Kontakt",
        "title": "Erstgespräch & Kontakt.",
        "text": "Wenn Sie Fragen haben oder ein Erstgespräch vereinbaren möchten, freue ich mich über Ihre Nachricht.",
        "addressLine1": "Adresse bitte ergänzen",
        "addressLine2": "",
        "phoneLabel": "Telefonnummer bitte ergänzen",
        "phoneHref": "",
        "email": "E-Mail-Adresse bitte ergänzen",
        "mapLink": "",
        "mapLabel": ""
      }
    }
  ],
  "footer": {
    "copyright": "© 2026 Carina Schmida, BA.pth."
  }
};
