/* Generated by editor.html. Do not edit this file manually. */
window.practiceContent = {
  "colorTheme": "ruby",
  "customColors": {},
  "sectionLayout": {
    "order": [
      "intro",
      "therapy",
      "focusAreas",
      "practice",
      "costs",
      "contact"
    ],
    "enabled": {
      "intro": true,
      "therapy": false,
      "focusAreas": true,
      "practice": true,
      "costs": true,
      "contact": true
    }
  },
  "practiceName": "Carina Schmida, BA.pth.",
  "practitionerName": "Dr. Anna Beispiel",
  "navigation": {
    "home": "Startseite",
    "psychotherapy": "Psychotherapie",
    "costs": "Kosten",
    "focusAreas": "Schwerpunkte",
    "contact": "Kontakt"
  },
  "hero": {
    "eyebrow": "Psychotherapeutin in Ausbildung unter Supervision",
    "title": "Gefühle annehmen.\nGedanken ordnen.\nLeben gestalten.",
    "sentence": "",
    "contactButton": "Kontakt aufnehmen"
  },
  "heroImage": {
    "src": "therapist.png",
    "alt": "Portraet der Therapeutin",
    "layout": "portrait",
    "blend": "duotone",
    "position": "center top",
    "overlay": "soft"
  },
  "introduction": {
    "title": "Manchmal hilft es, nicht allein weitergehen zu müssen.",
    "text": "Ob bei Ängsten, Depressionen oder sonstigen psychischen Krisen – als Verhaltenstherapeutin helfe ich Ihnen belastende Gefühle, Gedanken und Verhaltensweisen zu erkennen und schrittweise zu verändern. \n\nRespekt, Wertschätzung und Empathie bilden die Basis unserer Zusammenarbeit. In einem sicheren, geschützten Rahmen können Sie sich öffnen, vorhandene Stärken und Ressourcen wieder entdecken, hilfreiche Strategien zur Überwindung Ihrer individuellen Probleme erlernen und neue Wege erkunden. Das Ziel ist, dass Sie mehr Klarheit und Selbstwirksamkeit erlangen und damit mehr Lebensfreude und Wohlbefinden in Ihr Leben einziehen können. \n\nIch würde mich freuen, Sie kennenlernen und ein Stück auf Ihrem Weg in eine möglichst unbeschwerte Zukunft begleiten zu dürfen.",
    "items": [
      "",
      "",
      ""
    ]
  },
  "therapy": {
    "label": "Psychotherapie",
    "title": "Verstehen, was wirkt. Veraendern, was schwer geworden ist.",
    "text": "In unseren Gespraechen geht es um Ihre aktuellen Fragen, wiederkehrende Muster und um das, was Sie staerken kann. Die Zusammenarbeit richtet sich nach Ihrer Lebenssituation und Ihren Zielen.",
    "note": "Ein Erstgespraech gibt Ihnen Gelegenheit, mich und meine Arbeitsweise kennenzulernen. Danach entscheiden Sie in Ruhe, ob eine Zusammenarbeit fuer Sie stimmig ist."
  },
  "focusAreas": {
    "label": "Schwerpunkte",
    "title": "Womit Sie zu mir kommen können.",
    "intro": "Psychotherapie ist so individuell wie die Menschen, die zu mir kommen. Hier finden Sie einige Themen, bei denen ich Sie begleiten kann.",
    "areas": [
      [
        "Belastung & Erschoepfung",
        ""
      ],
      [
        "Beziehungen",
        ""
      ],
      [
        "Selbstwert",
        ""
      ],
      [
        "Uebergaenge",
        ""
      ],
      [
        "Neuer Schwerpunkt",
        "Kurze Beschreibung des Schwerpunkts."
      ],
      [
        "Neuer Schwerpunkt",
        "Kurze Beschreibung des Schwerpunkts."
      ]
    ]
  },
  "practice": {
    "label": "Die Praxis",
    "title": "Ein ruhiger Raum fuer Ihr Gespraech.",
    "text": "Die Praxis ist bewusst schlicht und ruhig gehalten. Sie erwartet ein ungestoerter Rahmen fuer vertrauliche Gespraeche.",
    "imageAlt": "Platzhalter fuer ein Foto des Praxisraums"
  },
  "costs": {
    "label": "Kosten",
    "title": "Transparent von Anfang an.",
    "intro": "Die Rahmenbedingungen besprechen wir im Erstgespraech. Bitte passen Sie die folgenden Angaben an Ihre Praxis an.",
    "entries": [
      [
        "Einzeltherapie",
        "50 Minuten",
        "EUR 110"
      ],
      [
        "Erstgespraech",
        "50 Minuten",
        "EUR 110"
      ],
      [
        "Absageregelung",
        "bis 48 Stunden vorher",
        "kostenfrei"
      ]
    ],
    "reimbursement": "Je nach Krankenkasse kann ein Kostenzuschuss moeglich sein. Details klaeren wir gerne persoenlich."
  },
  "contact": {
    "label": "Kontakt",
    "title": "Nehmen Sie Kontakt auf.",
    "text": "Sie koennen mich gerne per E-Mail oder telefonisch erreichen. Ich melde mich zeitnah bei Ihnen zurueck.",
    "address": [
      "Musterstrasse 12",
      "1010 Wien"
    ],
    "phoneLabel": "+43 660 123 45 67",
    "phoneHref": "+436601234567",
    "email": "praxis@beispiel.at",
    "mapLink": "https://www.openstreetmap.org/?mlat=48.2082&mlon=16.3738#map=15/48.2082/16.3738",
    "mapLabel": "Karte in OpenStreetMap oeffnen"
  },
  "footer": {
    "copyright": "2026 Praxis fuer Psychotherapie"
  }
};
